import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#181d14",
        "tertiary-container": "#d081a8",
        "outline": "#72796d",
        "on-secondary-container": "#672c00",
        "surface-variant": "#dfe5d6",
        "on-secondary-fixed": "#321200",
        "tertiary-fixed": "#ffd8e8",
        "on-primary-fixed": "#022100",
        "background": "#f6fcec",
        "surface-container": "#eaf0e1",
        "surface-bright": "#f6fcec",
        "surface": "#f6fcec",
        "primary-fixed": "#bdf1a8",
        "surface-dim": "#d6dccd",
        "outline-variant": "#c2c9ba",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#763300",
        "surface-container-highest": "#dfe5d6",
        "secondary": "#9a4600",
        "on-tertiary-fixed-variant": "#703053",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffafd5",
        "secondary-container": "#fe893c",
        "on-tertiary-fixed": "#3b0326",
        "surface-container-low": "#f0f6e6",
        "inverse-surface": "#2c3228",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a2d48e",
        "on-tertiary-container": "#561b3d",
        "on-error": "#ffffff",
        "on-surface-variant": "#42493e",
        "secondary-fixed-dim": "#ffb68d",
        "secondary-fixed": "#ffdbc9",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary": "#8c486c",
        "on-primary-container": "#0e3a05",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#a2d48e",
        "on-primary-fixed-variant": "#25501a",
        "primary-container": "#76a665",
        "surface-tint": "#3c692f",
        "primary": "#3c692f",
        "on-background": "#181d14",
        "surface-container-high": "#e4eadb",
        "inverse-on-surface": "#edf3e4",
        brown: "#CEBEA8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
